#
# Copyright 2026 Christoph Pospiech
#
"""Type stubs for the keepass pybind11 extension module."""

from enum import Enum

class PasswordError(Exception): ...
class FormatError(Exception): ...
class InternalError(Exception): ...
class IoError(Exception): ...
class FileNotFoundError(IoError): ...

class ProtectedString:
    def __init__(self, value: str = "", is_protected: bool = False) -> None: ...
    def is_protected(self) -> bool: ...
    def set_protected(self, prot: bool) -> None: ...
    def value(self) -> str: ...
    def set_value(self, value: str) -> None: ...

class TemporalString:
    def __init__(self, value: str = "", time: int = 0) -> None: ...
    def value(self) -> str: ...
    def time(self) -> int: ...
    def set_time(self, time: int) -> None: ...
    def Set(self, value: str) -> None: ...

class Cipher(Enum):
    kAes: Cipher
    kTwofish: Cipher

class SubKeyResolution(Enum):
    kHashSubKeys: SubKeyResolution
    kHashSubKeysOnlyIfCompositeKey: SubKeyResolution

kAes: Cipher
kTwofish: Cipher
kHashSubKeys: SubKeyResolution
kHashSubKeysOnlyIfCompositeKey: SubKeyResolution

class Key:
    def __init__(self, password: str = "") -> None: ...
    def SetPassword(self, password: str) -> None: ...
    def SetKeyFile(self, path: str) -> None: ...
    def Transform(self, seed: list[int], rounds: int, resolution: SubKeyResolution) -> list[int]: ...

class Binary:
    def __init__(self, data: ProtectedString) -> None: ...
    def Empty(self) -> bool: ...
    def Size(self) -> int: ...
    def data(self) -> ProtectedString: ...
    def set_data(self, data: ProtectedString) -> None: ...
    def compress(self) -> bool: ...
    def set_compress(self, compress: bool) -> None: ...

class Icon:
    def __init__(self, uuid: list[int], data: list[int]) -> None: ...
    def uuid(self) -> list[int]: ...
    def data(self) -> list[int]: ...
    def set_data(self, data: list[int]) -> None: ...

class Entry:
    class Attachment:
        def __init__(self) -> None: ...
        def name(self) -> str: ...
        def set_name(self, name: str) -> None: ...
        def binary(self) -> Binary | None: ...
        def set_binary(self, binary: Binary) -> None: ...
        def ToJson(self) -> str: ...

    class AutoType:
        class Association:
            def __init__(self, window: str, sequence: str) -> None: ...
            def window(self) -> str: ...
            def sequence(self) -> str: ...

        def __init__(self) -> None: ...
        def enabled(self) -> bool: ...
        def set_enabled(self, enabled: bool) -> None: ...
        def obfuscation(self) -> int: ...
        def set_obfuscation(self, obfuscation: bool) -> None: ...
        def sequence(self) -> str: ...
        def set_sequence(self, sequence: str) -> None: ...
        def associations(self) -> list[Association]: ...
        def AddAssociation(self, window: str, sequence: str) -> None: ...

    class Field:
        def __init__(self, key: str, value: ProtectedString) -> None: ...
        def key(self) -> str: ...
        def value(self) -> ProtectedString: ...

    def __init__(self) -> None: ...
    def uuid(self) -> list[int]: ...
    def set_uuid(self, uuid: list[int]) -> None: ...
    def icon(self) -> int: ...
    def set_icon(self, icon: int) -> None: ...
    def custom_icon(self) -> Icon | None: ...
    def set_custom_icon(self, icon: Icon) -> None: ...
    def title(self) -> ProtectedString: ...
    def set_title(self, title: ProtectedString) -> None: ...
    def url(self) -> ProtectedString: ...
    def set_url(self, url: ProtectedString) -> None: ...
    def override_url(self) -> str: ...
    def set_override_url(self, url: str) -> None: ...
    def username(self) -> ProtectedString: ...
    def set_username(self, username: ProtectedString) -> None: ...
    def password(self) -> ProtectedString: ...
    def set_password(self, password: ProtectedString) -> None: ...
    def notes(self) -> ProtectedString: ...
    def set_notes(self, notes: ProtectedString) -> None: ...
    def tags(self) -> str: ...
    def set_tags(self, tags: str) -> None: ...
    def creation_time(self) -> int: ...
    def set_creation_time(self, time: int) -> None: ...
    def modification_time(self) -> int: ...
    def set_modification_time(self, time: int) -> None: ...
    def access_time(self) -> int: ...
    def set_access_time(self, time: int) -> None: ...
    def expiry_time(self) -> int: ...
    def set_expiry_time(self, time: int) -> None: ...
    def move_time(self) -> int: ...
    def set_move_time(self, time: int) -> None: ...
    def expires(self) -> bool: ...
    def set_expires(self, expires: bool) -> None: ...
    def usage_count(self) -> int: ...
    def set_usage_count(self, usage_count: int) -> None: ...
    def bg_color(self) -> str: ...
    def set_bg_color(self, bg_color: str) -> None: ...
    def fg_color(self) -> str: ...
    def set_fg_color(self, fg_color: str) -> None: ...
    def auto_type(self) -> AutoType: ...
    def attachments(self) -> list[Attachment]: ...
    def history(self) -> list[Entry]: ...
    def custom_fields(self) -> list[Field]: ...
    def AddAttachment(self, attachment: Attachment) -> None: ...
    def HasAttachment(self) -> bool: ...
    def AddHistoryEntry(self, entry: Entry) -> None: ...
    def AddCustomField(self, key: str, value: ProtectedString) -> None: ...
    def HasNonDefaultAutoTypeSettings(self) -> bool: ...
    def IsMetaEntry(self) -> bool: ...
    def ToJson(self) -> str: ...

class Group:
    def __init__(self) -> None: ...
    def uuid(self) -> list[int]: ...
    def set_uuid(self, uuid: list[int]) -> None: ...
    def icon(self) -> int: ...
    def set_icon(self, icon: int) -> None: ...
    def custom_icon(self) -> Icon | None: ...
    def set_custom_icon(self, icon: Icon) -> None: ...
    def name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def notes(self) -> str: ...
    def set_notes(self, notes: str) -> None: ...
    def creation_time(self) -> int: ...
    def set_creation_time(self, time: int) -> None: ...
    def modification_time(self) -> int: ...
    def set_modification_time(self, time: int) -> None: ...
    def access_time(self) -> int: ...
    def set_access_time(self, time: int) -> None: ...
    def expiry_time(self) -> int: ...
    def set_expiry_time(self, time: int) -> None: ...
    def move_time(self) -> int: ...
    def set_move_time(self, time: int) -> None: ...
    def flags(self) -> int: ...
    def set_flags(self, flags: int) -> None: ...
    def expires(self) -> bool: ...
    def set_expires(self, expires: bool) -> None: ...
    def expanded(self) -> bool: ...
    def set_expanded(self, expanded: bool) -> None: ...
    def usage_count(self) -> int: ...
    def set_usage_count(self, usage_count: int) -> None: ...
    def default_autotype_sequence(self) -> str: ...
    def set_default_autotype_sequence(self, sequence: str) -> None: ...
    def autotype(self) -> bool: ...
    def set_autotype(self, autotype: bool) -> None: ...
    def search(self) -> bool: ...
    def set_search(self, search: bool) -> None: ...
    def last_visible_entry(self) -> Entry | None: ...
    def set_last_visible_entry(self, entry: Entry) -> None: ...
    def Groups(self) -> list[Group]: ...
    def Entries(self) -> list[Entry]: ...
    def AddGroup(self, group: Group) -> None: ...
    def AddEntry(self, entry: Entry) -> None: ...
    def HasNonMetaEntries(self) -> bool: ...
    def ToJson(self) -> str: ...

class Metadata:
    class MemoryProtection:
        def __init__(self) -> None: ...
        def title(self) -> bool: ...
        def set_title(self, title: bool) -> None: ...
        def username(self) -> bool: ...
        def set_username(self, username: bool) -> None: ...
        def password(self) -> bool: ...
        def set_password(self, password: bool) -> None: ...
        def url(self) -> bool: ...
        def set_url(self, url: bool) -> None: ...
        def notes(self) -> bool: ...
        def set_notes(self, notes: bool) -> None: ...

    class Field:
        def __init__(self, key: str, value: str) -> None: ...
        def key(self) -> str: ...
        def value(self) -> str: ...

    def __init__(self) -> None: ...
    def generator(self) -> str: ...
    def set_generator(self, generator: str) -> None: ...
    def database_name(self) -> TemporalString: ...
    def set_database_name(self, name: TemporalString) -> None: ...
    def database_desc(self) -> TemporalString: ...
    def set_database_desc(self, desc: TemporalString) -> None: ...
    def default_username(self) -> TemporalString: ...
    def set_default_username(self, username: TemporalString) -> None: ...
    def maintenance_hist_days(self) -> int: ...
    def set_maintenance_hist_days(self, days: int) -> None: ...
    def database_color(self) -> str: ...
    def set_database_color(self, color: str) -> None: ...
    def master_key_changed(self) -> int: ...
    def set_master_key_changed(self, time: int) -> None: ...
    def master_key_change_rec(self) -> int: ...
    def set_master_key_change_rec(self, rec: int) -> None: ...
    def master_key_change_force(self) -> int: ...
    def set_master_key_change_force(self, force: int) -> None: ...
    def memory_protection(self) -> MemoryProtection: ...
    def recycle_bin(self) -> Group | None: ...
    def set_recycle_bin(self, group: Group) -> None: ...
    def recycle_bin_changed(self) -> int: ...
    def set_recycle_bin_changed(self, time: int) -> None: ...
    def entry_templates(self) -> Group | None: ...
    def set_entry_templates(self, group: Group) -> None: ...
    def entry_templates_changed(self) -> int: ...
    def set_entry_templates_changed(self, time: int) -> None: ...
    def history_max_items(self) -> int: ...
    def set_history_max_items(self, max_items: int) -> None: ...
    def history_max_size(self) -> int: ...
    def set_history_max_size(self, max_size: int) -> None: ...
    def last_selected_group(self) -> Group | None: ...
    def set_last_selected_group(self, group: Group) -> None: ...
    def last_visible_group(self) -> Group | None: ...
    def set_last_visible_group(self, group: Group) -> None: ...
    def binaries(self) -> list[Binary]: ...
    def icons(self) -> list[Icon]: ...
    def fields(self) -> list[Field]: ...
    def AddBinary(self, binary: Binary) -> None: ...
    def AddIcon(self, icon: Icon) -> None: ...
    def AddField(self, key: str, value: str) -> None: ...

class Database:
    def __init__(self) -> None: ...
    def root(self) -> Group | None: ...
    def set_root(self, root: Group) -> None: ...
    def cipher(self) -> Cipher: ...
    def set_cipher(self, cipher: Cipher) -> None: ...
    def master_seed(self) -> list[int]: ...
    def set_master_seed(self, seed: list[int]) -> None: ...
    def init_vector(self) -> list[int]: ...
    def set_init_vector(self, iv: list[int]) -> None: ...
    def transform_seed(self) -> list[int]: ...
    def set_transform_seed(self, seed: list[int]) -> None: ...
    def inner_random_stream_key(self) -> list[int]: ...
    def set_inner_random_stream_key(self, key: list[int]) -> None: ...
    def transform_rounds(self) -> int: ...
    def set_transform_rounds(self, rounds: int) -> None: ...
    def compress(self) -> bool: ...
    def set_compress(self, compress: bool) -> None: ...
    def meta(self) -> Metadata | None: ...
    def set_meta(self, meta: Metadata) -> None: ...

class KdbFile:
    def __init__(self) -> None: ...
    def Import(self, path: str, key: Key) -> Database: ...
    def Export(self, path: str, db: Database, key: Key) -> None: ...

class KdbxFile:
    def __init__(self) -> None: ...
    def Import(self, path: str, key: Key) -> Database: ...
    def Export(self, path: str, db: Database, key: Key) -> None: ...
