#
# Copyright 2026 Christoph Pospiech
#
"""Type stubs for the kwallet pybind11 extension module.

Generated to suppress false PyLance import errors.
"""

from collections.abc import Iterator

class WalletHandle:
    def __init__(self, name: str) -> None: ...
    def wallet_is_open(self) -> bool: ...
    def wallet_name(self) -> str: ...
    def hasFolder(self, folder: str) -> bool: ...
    def setFolder(self, folder: str) -> bool: ...
    def currentFolder(self) -> str: ...
    def password(self, key: str) -> str: ...
    def username(self, key: str) -> str: ...
    def hostname(self, key: str) -> str: ...

class WalletIterator:
    def __init__(self, wallet: WalletHandle) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
